// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appplatform.implementation;

import com.azure.resourcemanager.appplatform.AppPlatformManager;
import com.azure.resourcemanager.appplatform.fluent.models.ApiPortalResourceInner;
import com.azure.resourcemanager.appplatform.models.SpringApiPortal;
import com.azure.resourcemanager.appplatform.models.SpringApiPortals;
import com.azure.resourcemanager.appplatform.models.SpringService;
import com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.ExternalChildResourcesNonCachedImpl;

public class SpringApiPortalsImpl
    extends ExternalChildResourcesNonCachedImpl<SpringApiPortalImpl, SpringApiPortal, ApiPortalResourceInner, SpringServiceImpl, SpringService>
    implements SpringApiPortals {

    protected SpringApiPortalsImpl(SpringServiceImpl parentImpl) {
        super(parentImpl, parentImpl.taskGroup(), "SpringApiPortal");
    }

    @Override
    public AppPlatformManager manager() {
        return getParent().manager();
    }

    @Override
    public SpringService parent() {
        return getParent();
    }

    public void prepareCreate() {
        prepareInlineDefine(
            new SpringApiPortalImpl(Constants.DEFAULT_TANZU_COMPONENT_NAME, getParent(), new ApiPortalResourceInner())
        );
    }
}
