// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appplatform.implementation;

import com.azure.resourcemanager.appplatform.AppPlatformManager;
import com.azure.resourcemanager.appplatform.fluent.models.GatewayResourceInner;
import com.azure.resourcemanager.appplatform.models.SpringCloudGateway;
import com.azure.resourcemanager.appplatform.models.SpringCloudGateways;
import com.azure.resourcemanager.appplatform.models.SpringService;
import com.azure.resourcemanager.resources.fluentcore.arm.collection.implementation.ExternalChildResourcesNonCachedImpl;

public class SpringCloudGatewaysImpl
    extends ExternalChildResourcesNonCachedImpl<SpringCloudGatewayImpl, SpringCloudGateway, GatewayResourceInner, SpringServiceImpl, SpringService>
    implements SpringCloudGateways {

    public SpringCloudGatewaysImpl(SpringServiceImpl parentImpl) {
        super(parentImpl, parentImpl.taskGroup(), "SpringCloudGateway");
    }

    @Override
    public AppPlatformManager manager() {
        return parent().manager();
    }

    @Override
    public SpringService parent() {
        return getParent();
    }

    public void prepareCreate() {
        prepareInlineDefine(
            new SpringCloudGatewayImpl(
                Constants.DEFAULT_TANZU_COMPONENT_NAME,
                getParent(),
                new GatewayResourceInner()
            )
        );
    }
}
