// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appplatform;

import com.azure.core.management.Region;
import com.azure.resourcemanager.appplatform.models.SpringApp;
import com.azure.resourcemanager.appplatform.models.SpringService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

public class EnterpriseTierTest extends AppPlatformTest {

    private static final String GIT_CONFIG_URI = "https://github.com/Azure-Samples/spring-petclinic-microservices-config";

    @Test
    public void canCRUDService() {
        String serviceName = generateRandomResourceName("springsvc", 15);
        Region region = Region.US_EAST;
        // define spring cloud service for enterprise tier
        List<String> filePatterns = new ArrayList<>();
        filePatterns.add("api-gateway");
        SpringService springService = appPlatformManager.springServices()
            .define(serviceName)
            .withRegion(region)
            .withNewResourceGroup(rgName)
            .withEnterpriseTierSku()
            .withGitConfig(GIT_CONFIG_URI, "master", filePatterns)
            .create();

        // tanzu components
//        SpringServiceRegistry serviceRegistry = springService.serviceRegistry();
//        SpringCloudGateway gateway = springService.springCloudGateway();
//        SpringApiPortal apiPortal = springService.apiPortal();
//        Assertions.assertNotNull(serviceRegistry);
//        Assertions.assertNotNull(gateway);
//        Assertions.assertNotNull(apiPortal);
        Assertions.assertEquals(springService.getDefaultConfigurationService().gitUri(), GIT_CONFIG_URI);
        Assertions.assertEquals(springService.getDefaultConfigurationService().filePatterns(), filePatterns);
//        Assertions.assertNotNull(serviceRegistry.cpu());
//        Assertions.assertNotNull(gateway.cpu());
//        Assertions.assertNotNull(apiPortal.cpu());
//        Assertions.assertNotNull(configurationService.cpu());

        springService.update()
            .withoutGitConfig()
            .apply();

        Assertions.assertNull(springService.getDefaultConfigurationService().gitUri());
    }

    @Test
    public void canCRUDApp() {
        String serviceName = generateRandomResourceName("springsvc", 15);
        Region region = Region.US_EAST;
        // define spring cloud service for enterprise tier
        List<String> filePatterns = new ArrayList<>();
        filePatterns.add("api-gateway");
        SpringService springService = appPlatformManager.springServices()
            .define(serviceName)
            .withRegion(region)
            .withNewResourceGroup(rgName)
            .withEnterpriseTierSku()
            .withGitConfig(GIT_CONFIG_URI, "master", filePatterns)
            .create();

        String appName = generateRandomResourceName("springapp", 15);
        SpringApp app = springService.apps()
            .define(appName)
            .withDefaultActiveDeployment()
            .withConfigurationServiceBinding()
            .withServiceRegistryBinding()
            .withHttpsOnly()
            .withDefaultPublicEndpoint()
            .create();

        Assertions.assertNotNull(app.url());
        Assertions.assertTrue(app.isHttpsOnly());
        Assertions.assertTrue(app.isPublic());
        Assertions.assertTrue(app.hasConfigurationServiceBinding());
        Assertions.assertTrue(app.hasServiceRegistryBinding());
        Assertions.assertTrue(springService.getDefaultConfigurationService().getAppBindings().stream().anyMatch(SpringApp::hasConfigurationServiceBinding));
        Assertions.assertTrue(springService.getDefaultServiceRegistry().getAppBindings().stream().anyMatch(SpringApp::hasServiceRegistryBinding));

        app.update()
            .withoutHttpsOnly()
            .withoutConfigurationServiceBinding()
            .withoutServiceRegistryBinding()
            .withoutDefaultPublicEndpoint()
            .apply();

        Assertions.assertFalse(app.isHttpsOnly());
        Assertions.assertFalse(app.isPublic());
        Assertions.assertFalse(app.hasConfigurationServiceBinding());
        Assertions.assertFalse(app.hasServiceRegistryBinding());
        Assertions.assertFalse(springService.getDefaultConfigurationService().getAppBindings().stream().anyMatch(SpringApp::hasConfigurationServiceBinding));
        Assertions.assertFalse(springService.getDefaultServiceRegistry().getAppBindings().stream().anyMatch(SpringApp::hasServiceRegistryBinding));
    }
}
