// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.search.documents.knowledgebases;

import com.azure.json.JsonProviders;
import com.azure.json.JsonReader;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseActivityRecord;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseActivityStartedEvent;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseAnswerCompletedEvent;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseReference;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseResponseCompletedEvent;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseRetrievalStartedEvent;
import com.azure.search.documents.knowledgebases.models.KnowledgeBaseStreamErrorEvent;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.List;

final class KnowledgeBaseRetrievalStreamEvents {
    private KnowledgeBaseRetrievalStreamEvents() {
    }

    static KnowledgeBaseRetrievalStreamEvent deserialize(String eventName, String data) {
        if (eventName == null || data == null) {
            return null;
        }

        try (JsonReader reader = JsonProviders.createReader(data.getBytes(StandardCharsets.UTF_8))) {
            switch (eventName) {
                case "retrieval.started":
                    return KnowledgeBaseRetrievalStreamEvent
                        .ofRetrievalStarted(KnowledgeBaseRetrievalStartedEvent.fromJson(reader));

                case "activity.started":
                    return KnowledgeBaseRetrievalStreamEvent
                        .ofActivityStarted(KnowledgeBaseActivityStartedEvent.fromJson(reader));

                case "activity.completed":
                    return KnowledgeBaseRetrievalStreamEvent
                        .ofActivityCompleted(KnowledgeBaseActivityRecord.fromJson(reader));

                case "answer.completed":
                    return KnowledgeBaseRetrievalStreamEvent
                        .ofAnswerCompleted(KnowledgeBaseAnswerCompletedEvent.fromJson(reader));

                case "references.completed":
                    List<KnowledgeBaseReference> references = reader.readArray(KnowledgeBaseReference::fromJson);
                    return KnowledgeBaseRetrievalStreamEvent.ofReferencesCompleted(references);

                case "error":
                    return KnowledgeBaseRetrievalStreamEvent.ofError(KnowledgeBaseStreamErrorEvent.fromJson(reader));

                case "response.completed":
                    return KnowledgeBaseRetrievalStreamEvent
                        .ofResponseCompleted(KnowledgeBaseResponseCompletedEvent.fromJson(reader));

                default:
                    return KnowledgeBaseRetrievalStreamEvent.ofUnknown();
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
