// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appplatform.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.appplatform.fluent.models.GatewayResourceInner;
import com.azure.resourcemanager.resources.fluentcore.arm.models.ExternalChildResource;
import com.azure.resourcemanager.resources.fluentcore.model.HasInnerModel;

@Fluent
public interface SpringCloudGateway
    extends ExternalChildResource<SpringCloudGateway, SpringService>,
    HasInnerModel<GatewayResourceInner> {

    /** @return cpu for the Spring Cloud Gateway */
    String cpu();

    /** @return memory for the Spring Cloud Gateway */
    String memory();
}
