// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appplatform.models;

import com.azure.core.annotation.Fluent;

@Fluent
public interface SpringApiPortal {
    /** @return cpu for Spring API Portal */
    String cpu();

    /** @return memory for Spring API Portal*/
    String memory();
}
