// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appplatform.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.appplatform.fluent.models.BuildServiceInner;
import com.azure.resourcemanager.resources.fluentcore.arm.models.ExternalChildResource;
import com.azure.resourcemanager.resources.fluentcore.model.HasInnerModel;

/** An immutable client-side representation of an Azure Spring Cloud Build Service. */
@Fluent
public interface SpringBuildService
    extends ExternalChildResource<SpringBuildService, SpringService>,
    HasInnerModel<BuildServiceInner> {

    /** @return cpu for the Build Service */
    String cpu();

    /** @return memory for the Build Service */
    String memory();
}
