// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicefabricmanagedclusters.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Managed data disk type. Specifies the storage account type for the managed disk.
 */
public final class DiskType extends ExpandableStringEnum<DiskType> {
    /**
     * Static value Standard_LRS for DiskType.
     */
    public static final DiskType STANDARD_LRS = fromString("Standard_LRS");

    /**
     * Static value StandardSSD_LRS for DiskType.
     */
    public static final DiskType STANDARD_SSD_LRS = fromString("StandardSSD_LRS");

    /**
     * Static value Premium_LRS for DiskType.
     */
    public static final DiskType PREMIUM_LRS = fromString("Premium_LRS");

    /**
     * Static value PremiumV2_LRS for DiskType.
     */
    public static final DiskType PREMIUM_V2_LRS = fromString("PremiumV2_LRS");

    /**
     * Static value StandardSSD_ZRS for DiskType.
     */
    public static final DiskType STANDARD_SSD_ZRS = fromString("StandardSSD_ZRS");

    /**
     * Static value Premium_ZRS for DiskType.
     */
    public static final DiskType PREMIUM_ZRS = fromString("Premium_ZRS");

    /**
     * Creates a new instance of DiskType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public DiskType() {
    }

    /**
     * Creates or finds a DiskType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding DiskType.
     */
    public static DiskType fromString(String name) {
        return fromString(name, DiskType.class);
    }

    /**
     * Gets known DiskType values.
     * 
     * @return known DiskType values.
     */
    public static Collection<DiskType> values() {
        return values(DiskType.class);
    }
}
