// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicefabricmanagedclusters.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Fault simulation status.
 */
public final class FaultSimulationStatus extends ExpandableStringEnum<FaultSimulationStatus> {
    /**
     * Static value Starting for FaultSimulationStatus.
     */
    public static final FaultSimulationStatus STARTING = fromString("Starting");

    /**
     * Static value Active for FaultSimulationStatus.
     */
    public static final FaultSimulationStatus ACTIVE = fromString("Active");

    /**
     * Static value Stopping for FaultSimulationStatus.
     */
    public static final FaultSimulationStatus STOPPING = fromString("Stopping");

    /**
     * Static value Done for FaultSimulationStatus.
     */
    public static final FaultSimulationStatus DONE = fromString("Done");

    /**
     * Static value StartFailed for FaultSimulationStatus.
     */
    public static final FaultSimulationStatus START_FAILED = fromString("StartFailed");

    /**
     * Static value StopFailed for FaultSimulationStatus.
     */
    public static final FaultSimulationStatus STOP_FAILED = fromString("StopFailed");

    /**
     * Creates a new instance of FaultSimulationStatus value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public FaultSimulationStatus() {
    }

    /**
     * Creates or finds a FaultSimulationStatus from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding FaultSimulationStatus.
     */
    public static FaultSimulationStatus fromString(String name) {
        return fromString(name, FaultSimulationStatus.class);
    }

    /**
     * Gets known FaultSimulationStatus values.
     * 
     * @return known FaultSimulationStatus values.
     */
    public static Collection<FaultSimulationStatus> values() {
        return values(FaultSimulationStatus.class);
    }
}
