// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicefabricmanagedclusters.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Sfmc operation status.
 */
public final class SfmcOperationStatus extends ExpandableStringEnum<SfmcOperationStatus> {
    /**
     * Static value Created for SfmcOperationStatus.
     */
    public static final SfmcOperationStatus CREATED = fromString("Created");

    /**
     * Static value Started for SfmcOperationStatus.
     */
    public static final SfmcOperationStatus STARTED = fromString("Started");

    /**
     * Static value Succeeded for SfmcOperationStatus.
     */
    public static final SfmcOperationStatus SUCCEEDED = fromString("Succeeded");

    /**
     * Static value Failed for SfmcOperationStatus.
     */
    public static final SfmcOperationStatus FAILED = fromString("Failed");

    /**
     * Static value Aborted for SfmcOperationStatus.
     */
    public static final SfmcOperationStatus ABORTED = fromString("Aborted");

    /**
     * Static value Canceled for SfmcOperationStatus.
     */
    public static final SfmcOperationStatus CANCELED = fromString("Canceled");

    /**
     * Creates a new instance of SfmcOperationStatus value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public SfmcOperationStatus() {
    }

    /**
     * Creates or finds a SfmcOperationStatus from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding SfmcOperationStatus.
     */
    public static SfmcOperationStatus fromString(String name) {
        return fromString(name, SfmcOperationStatus.class);
    }

    /**
     * Gets known SfmcOperationStatus values.
     * 
     * @return known SfmcOperationStatus values.
     */
    public static Collection<SfmcOperationStatus> values() {
        return values(SfmcOperationStatus.class);
    }
}
