// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.contentsafety {
    requires transitive com.azure.core;

    exports com.contentsafety;
    exports com.contentsafety.models;

    opens com.contentsafety.models to
            com.azure.core,
            com.fasterxml.jackson.databind;
}
